version: "3.8"
services:
  nextcloud:
    image: nextcloud:fpm-alpine
    volumes:
      - data:/var/www/html
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_UPDATE=1
  nginx:
    image: nginx:stable-alpine
    volumes:
      - data:/var/www/html:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextcloud
    restart: unless-stopped
  cron:
    image: nextcloud:fpm-alpine
    volumes:
      - data:/var/www/html
    restart: unless-stopped
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
  db:
    image: mariadb:latest
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    volumes:
      - cache:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
volumes:
  data:
  db:
  cache:
